extern int loadUserFile();
extern void listFileInfo();
extern int ChangeDictionry();
extern int deleteFile();
extern void menu();
extern void printChar();
extern void cprintf();
extern char getchar(); 
extern void backspace();
extern void clr();
extern void gettime();
extern void exe();
extern void intCall();
extern void Process();
extern void stackCopy();
extern int fork();
extern int wait();
extern void exit();

#define KERNAL_SEG 0x1000
#define USER_PRO_OFF 0x7e00
#define USER_PRS_OFF 0x100

#define Black 0
#define Blue 1
#define Green 2
#define ColbaltBlue 3
#define Red 4
#define Violet 5
#define Brown 6
#define LightGrey 7 
#define DarkGrey 8
#define LightBlue 9
#define LightGreen 10
#define LightCobalt 11
#define LightRed 12 
#define LightViolet 13 
#define Yellow 14 
#define White 15